/**
 * MCP Builder — Generates working MCP server scaffolds.
 *
 * Takes a spec (service name, auth type, tools, resources) and produces
 * a complete, runnable MCP server using the official @modelcontextprotocol/sdk.
 */

/**
 * Generate MCP server files from a spec.
 *
 * @param {Object} spec
 * @param {string} spec.name - Service name (e.g., "github", "stripe")
 * @param {string} spec.description - What the MCP does
 * @param {string} spec.authType - "api_key" | "oauth" | "none"
 * @param {string} spec.authEnvVar - Env var name for the key (e.g., "GITHUB_TOKEN")
 * @param {Array} spec.tools - Array of { name, description, parameters }
 * @param {Array} spec.resources - Array of { name, description, uri }
 * @param {string} spec.baseUrl - API base URL (optional)
 */
export function generateMcp(spec) {
  const {
    name = "my-service",
    description = "MCP server for " + name,
    authType = "api_key",
    authEnvVar = name.toUpperCase().replace(/[^A-Z0-9]/g, "_") + "_API_KEY",
    tools = [],
    resources = [],
    baseUrl = "https://api.example.com",
  } = spec;

  const slug = name.toLowerCase().replace(/[^a-z0-9]+/g, "-");

  const serverCode = buildServerCode({ slug, name, description, authType, authEnvVar, tools, resources, baseUrl });
  const packageJson = buildPackageJson({ slug, description });
  const readme = buildReadme({ slug, name, description, authType, authEnvVar, tools, resources });
  const mcpConfig = buildMcpConfig({ slug, authEnvVar });

  return {
    name: slug,
    files: {
      "server.mjs": serverCode,
      "package.json": packageJson,
      "README.md": readme,
      ".mcp.json": mcpConfig,
    },
  };
}

function buildServerCode({ slug, name, description, authType, authEnvVar, tools, resources, baseUrl }) {
  const toolHandlers = tools.map((t) => {
    const params = (t.parameters || [])
      .map((p) => `          ${p.name}: { type: "${p.type || "string"}", description: "${p.description || ""}" },`)
      .join("\n");

    return `
  server.tool("${t.name}", "${t.description}", {
    ${params ? `properties: {\n${params}\n        },` : ""}
  }, async (args) => {
    const response = await fetch(\`${baseUrl}/${t.name.replace(/_/g, "/")}\`, {
      method: "GET",
      headers: authHeaders,
    });
    const data = await response.json();
    return { content: [{ type: "text", text: JSON.stringify(data, null, 2) }] };
  });`;
  }).join("\n");

  const resourceHandlers = resources.map((r) => `
  server.resource("${r.name}", "${r.uri || r.name}", "${r.description}", async () => {
    const response = await fetch(\`${baseUrl}/${r.name}\`, { headers: authHeaders });
    const data = await response.json();
    return { content: [{ type: "text", text: JSON.stringify(data, null, 2) }] };
  });`).join("\n");

  const authSetup = authType === "api_key"
    ? `const API_KEY = process.env.${authEnvVar};
if (!API_KEY) {
  console.error("Set ${authEnvVar} environment variable");
  process.exit(1);
}
const authHeaders = { "Authorization": \`Bearer \${API_KEY}\` };`
    : authType === "none"
    ? `const authHeaders = {};`
    : `// OAuth setup — configure your OAuth flow here
const authHeaders = {};`;

  return `#!/usr/bin/env node

/**
 * ${name} MCP Server
 * ${description}
 *
 * Generated by skill-builder (https://github.com/Scottpedia0/skill-builder)
 */

import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";

${authSetup}

const server = new McpServer({
  name: "${slug}",
  version: "1.0.0",
});
${toolHandlers}
${resourceHandlers}

const transport = new StdioServerTransport();
await server.connect(transport);
`;
}

function buildPackageJson({ slug, description }) {
  return JSON.stringify({
    name: slug + "-mcp",
    version: "1.0.0",
    description,
    type: "module",
    bin: { [slug + "-mcp"]: "./server.mjs" },
    dependencies: {
      "@modelcontextprotocol/sdk": "^1.12.0",
    },
  }, null, 2);
}

function buildReadme({ slug, name, description, authType, authEnvVar, tools, resources }) {
  const toolList = tools.length
    ? tools.map((t) => `| \`${t.name}\` | ${t.description} |`).join("\n")
    : "| (none yet) | Add tools in the spec |";

  const resourceList = resources.length
    ? resources.map((r) => `| \`${r.name}\` | ${r.description} |`).join("\n")
    : "| (none yet) | Add resources in the spec |";

  const authInstructions = authType === "api_key"
    ? `Set \`${authEnvVar}\` in your environment:\n\`\`\`bash\nexport ${authEnvVar}=your-key-here\n\`\`\``
    : authType === "none"
    ? "No authentication required."
    : "Configure OAuth credentials (see server.mjs).";

  return `# ${name} MCP Server

${description}

## Setup

\`\`\`bash
npm install
${authInstructions}
\`\`\`

## Usage

Add to your Claude Code config (\`~/.claude/settings.json\`):

\`\`\`json
{
  "mcpServers": {
    "${slug}": {
      "command": "node",
      "args": ["${process.cwd()}/${slug}-mcp/server.mjs"],
      "env": { "${authEnvVar}": "your-key" }
    }
  }
}
\`\`\`

## Tools

| Tool | Description |
|------|-------------|
${toolList}

## Resources

| Resource | Description |
|----------|-------------|
${resourceList}

---

Generated by [skill-builder](https://github.com/Scottpedia0/skill-builder)
`;
}

function buildMcpConfig({ slug, authEnvVar }) {
  return JSON.stringify({
    mcpServers: {
      [slug]: {
        command: "node",
        args: ["./server.mjs"],
        env: { [authEnvVar]: "" },
      },
    },
  }, null, 2);
}
